version: "3.8"
services:
  mysql:
    image: mysql:8.0.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - "./docker/mysql/data/:/var/lib/mysql"
      - "./docker/mysql/conf/:/etc/mysql/conf.d"
  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - "./docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./docker/redis/data/:/data/"
    command: /bin/sh -c "redis-server /usr/local/etc/redis/redis.conf --appendonly yes" # 指定配置文件并开启持久化
    privileged: true # 使用该参数，container内的root拥有真正的root权限。否则，container内的root只是外部的一个普通用户权限
